### PR TITLE
Breck newfields

### PR DESCRIPTION
**Pull request by abbistani**

### CODE REVIEW

**Comment by mark-cooper** [comment]
@abbistani there are changes to the defaults here. That will impact everyone. Are these changes that are already in core? Default changes should only mirror updates in core.

**Comment by abbistani** [comment]
@mark-cooper It looks like we need the whole base-vocabularies in the tenant because the <include> that we're changing is at the top level of the xml, so there's no identifiable section for the merge tool to replace.

**Comment by mark-cooper** [comment]
@abbistani @remillet alright. But I just want to clarify something first:

You have an entire copy of base-vocabularies.xml (breckenridge-base-vocabularies.xml) to include the line: `<include src="breckenridge-base-instance-vocabularies.xml" />`.

The thing that is breckenridge-base-instance-vocabularies.xml contains (I'm guessing) new and / or modified vocabs from the defaults for breckenridge. But isn't that the role of domain-instance-vocabularies.xml? Most (all?) tenants have one:

https://github.com/collectionspace/application/tree/master/tomcat-main/src/main/resources/tenants

But I don't see any other tenant copy / override base-instance-vocabularies in the way it's being done here. One possible exception (not quite the same):

https://github.com/collectionspace/application/tree/master/tomcat-main/src/main/resources/tenants/botgarden

Looks like @remillet did that. No base-vocabularies.xml present. @remillet do you mind being the final reviewer for this one and merge when you agree the approach is sound. Thx.

**Comment by abbistani** [comment]
@mark-cooper @remillet I'm happy to structure this any way you guys want, but we need to get Breck's site up for them.  Just tell me what to do.  Thanks.

**Comment by abbistani** [comment]
@mark-cooper, @remillet helped me do this the official way.  Basically, a base-instance-vocabularies.xml in the tenant directory will be preferred to the one in defaults without any need for includes or merges.  We still have a big file to diff on upgrades (until 5.0) but this is much simpler.

**Pull request merged**
